
#include <stdint.h>
#include <systemlib/param/param.h>

// DO NOT EDIT
// This file is autogenerated from parameters.xml

__BEGIN_DECLS

struct px4_parameters_t {

	/*****************************************************************
	 * Angular Velocity L1 Adaptive Control
	 ****************************************************************/
	const struct param_info_s __param__L1A_ACTIVE;
	const struct param_info_s __param__L1A_ENABLE_DEBUG;
	const struct param_info_s __param__L1A_BANDWIDTH_X;
	const struct param_info_s __param__L1A_BANDWIDTH_Y;
	const struct param_info_s __param__L1A_BANDWIDTH_Z;
	const struct param_info_s __param__L1A_OBSERVER_GAIN_X;
	const struct param_info_s __param__L1A_OBSERVER_GAIN_Y;
	const struct param_info_s __param__L1A_OBSERVER_GAIN_Z;
	const struct param_info_s __param__L1A_ADAPTATION_GAIN;
	const struct param_info_s __param__L1A_INIT_DISTX;
	const struct param_info_s __param__L1A_INIT_DISTY;
	const struct param_info_s __param__L1A_INIT_DISTZ;
	const struct param_info_s __param__L1A_ENGAGE_LEVEL;
	/*****************************************************************
	 * Attitude EKF estimator
	 ****************************************************************/
	const struct param_info_s __param__EKF_ATT_V3_Q0;
	const struct param_info_s __param__EKF_ATT_V3_Q1;
	const struct param_info_s __param__EKF_ATT_V3_Q2;
	const struct param_info_s __param__EKF_ATT_V3_Q3;
	const struct param_info_s __param__EKF_ATT_V4_R0;
	const struct param_info_s __param__EKF_ATT_V4_R1;
	const struct param_info_s __param__EKF_ATT_V4_R2;
	const struct param_info_s __param__ATT_J11;
	const struct param_info_s __param__ATT_J22;
	const struct param_info_s __param__ATT_J33;
	const struct param_info_s __param__ATT_J_EN;
	/*****************************************************************
	 * Attitude Q estimator
	 ****************************************************************/
	const struct param_info_s __param__ATT_W_ACC;
	const struct param_info_s __param__ATT_W_MAG;
	const struct param_info_s __param__ATT_W_EXT_HDG;
	const struct param_info_s __param__ATT_W_GYRO_BIAS;
	const struct param_info_s __param__ATT_MAG_DECL;
	const struct param_info_s __param__ATT_MAG_DECL_A;
	const struct param_info_s __param__ATT_EXT_HDG_M;
	const struct param_info_s __param__ATT_ACC_COMP;
	const struct param_info_s __param__ATT_BIAS_MAX;
	const struct param_info_s __param__ATT_VIBE_THRESH;
	/*****************************************************************
	 * Battery Calibration
	 ****************************************************************/
	const struct param_info_s __param__BAT_V_EMPTY;
	const struct param_info_s __param__BAT_V_CHARGED;
	const struct param_info_s __param__BAT_V_LOAD_DROP;
	const struct param_info_s __param__BAT_N_CELLS;
	const struct param_info_s __param__BAT_CAPACITY;
	const struct param_info_s __param__BAT_V_SCALE_IO;
	const struct param_info_s __param__BAT_V_SCALING;
	const struct param_info_s __param__BAT_C_SCALING;
	/*****************************************************************
	 * Camera trigger
	 ****************************************************************/
	const struct param_info_s __param__TRIG_INTERVAL;
	const struct param_info_s __param__TRIG_POLARITY;
	const struct param_info_s __param__TRIG_ACT_TIME;
	const struct param_info_s __param__TRIG_MODE;
	const struct param_info_s __param__TRIG_PINS;
	/*****************************************************************
	 * Circuit Breaker
	 ****************************************************************/
	const struct param_info_s __param__CBRK_SUPPLY_CHK;
	const struct param_info_s __param__CBRK_RATE_CTRL;
	const struct param_info_s __param__CBRK_IO_SAFETY;
	const struct param_info_s __param__CBRK_AIRSPD_CHK;
	const struct param_info_s __param__CBRK_FLIGHTTERM;
	const struct param_info_s __param__CBRK_ENGINEFAIL;
	const struct param_info_s __param__CBRK_GPSFAIL;
	const struct param_info_s __param__CBRK_BUZZER;
	const struct param_info_s __param__CBRK_USB_CHK;
	/*****************************************************************
	 * Commander
	 ****************************************************************/
	const struct param_info_s __param__COM_DL_LOSS_EN;
	const struct param_info_s __param__COM_DL_LOSS_T;
	const struct param_info_s __param__COM_DL_REG_T;
	const struct param_info_s __param__COM_EF_THROT;
	const struct param_info_s __param__COM_EF_C2T;
	const struct param_info_s __param__COM_EF_TIME;
	const struct param_info_s __param__COM_RC_LOSS_T;
	const struct param_info_s __param__COM_HOME_H_T;
	const struct param_info_s __param__COM_HOME_V_T;
	const struct param_info_s __param__COM_AUTOS_PAR;
	const struct param_info_s __param__COM_RC_IN_MODE;
	const struct param_info_s __param__COM_DISARM_LAND;
	/*****************************************************************
	 * Data Link Loss
	 ****************************************************************/
	const struct param_info_s __param__NAV_AH_LAT;
	const struct param_info_s __param__NAV_AH_LON;
	const struct param_info_s __param__NAV_AH_ALT;
	const struct param_info_s __param__NAV_DLL_CH_T;
	const struct param_info_s __param__NAV_DLL_CH_LAT;
	const struct param_info_s __param__NAV_DLL_CH_LON;
	const struct param_info_s __param__NAV_DLL_CH_ALT;
	const struct param_info_s __param__NAV_DLL_AH_T;
	const struct param_info_s __param__NAV_DLL_N;
	const struct param_info_s __param__NAV_DLL_CHSK;
	/*****************************************************************
	 * EKF2
	 ****************************************************************/
	const struct param_info_s __param__EKF2_MAG_DELAY;
	const struct param_info_s __param__EKF2_BARO_DELAY;
	const struct param_info_s __param__EKF2_GPS_DELAY;
	const struct param_info_s __param__EKF2_ASP_DELAY;
	const struct param_info_s __param__EKF2_REQ_EPH;
	const struct param_info_s __param__EKF2_REQ_EPV;
	const struct param_info_s __param__EKF2_G_NOISE;
	const struct param_info_s __param__EKF2_ACC_NOISE;
	const struct param_info_s __param__EKF2_GB_NOISE;
	const struct param_info_s __param__EKF2_ACCB_NOISE;
	const struct param_info_s __param__EKF2_GS_NOISE;
	const struct param_info_s __param__EKF2_MAG_NOISE;
	const struct param_info_s __param__EKF2_WIND_NOISE;
	const struct param_info_s __param__EKF2_GPS_V_NOISE;
	const struct param_info_s __param__EKF2_GPS_P_NOISE;
	const struct param_info_s __param__EKF2_BARO_NOISE;
	const struct param_info_s __param__EKF2_HEAD_NOISE;
	const struct param_info_s __param__EKF2_MAG_DECL;
	const struct param_info_s __param__EKF2_H_INOV_GATE;
	/*****************************************************************
	 * FW Attitude Control
	 ****************************************************************/
	const struct param_info_s __param__FW_R_TC;
	const struct param_info_s __param__FW_P_TC;
	const struct param_info_s __param__FW_PR_P;
	const struct param_info_s __param__FW_PR_I;
	const struct param_info_s __param__FW_P_RMAX_POS;
	const struct param_info_s __param__FW_P_RMAX_NEG;
	const struct param_info_s __param__FW_PR_IMAX;
	const struct param_info_s __param__FW_RR_P;
	const struct param_info_s __param__FW_RR_I;
	const struct param_info_s __param__FW_RR_IMAX;
	const struct param_info_s __param__FW_R_RMAX;
	const struct param_info_s __param__FW_YR_P;
	const struct param_info_s __param__FW_YR_I;
	const struct param_info_s __param__FW_YR_IMAX;
	const struct param_info_s __param__FW_Y_RMAX;
	const struct param_info_s __param__FW_WR_P;
	const struct param_info_s __param__FW_WR_I;
	const struct param_info_s __param__FW_WR_IMAX;
	const struct param_info_s __param__FW_W_RMAX;
	const struct param_info_s __param__FW_RR_FF;
	const struct param_info_s __param__FW_PR_FF;
	const struct param_info_s __param__FW_YR_FF;
	const struct param_info_s __param__FW_WR_FF;
	const struct param_info_s __param__FW_YCO_VMIN;
	const struct param_info_s __param__FW_YCO_METHOD;
	const struct param_info_s __param__FW_AIRSPD_MIN;
	const struct param_info_s __param__FW_AIRSPD_TRIM;
	const struct param_info_s __param__FW_AIRSPD_MAX;
	const struct param_info_s __param__FW_RSP_OFF;
	const struct param_info_s __param__FW_PSP_OFF;
	const struct param_info_s __param__FW_MAN_R_MAX;
	const struct param_info_s __param__FW_MAN_P_MAX;
	const struct param_info_s __param__FW_FLAPS_SCL;
	const struct param_info_s __param__FW_FLAPERON_SCL;
	/*****************************************************************
	 * Fixed Wing TECS
	 ****************************************************************/
	const struct param_info_s __param__FW_T_SINK_MIN;
	const struct param_info_s __param__FW_T_SINK_MAX;
	const struct param_info_s __param__FW_T_TIME_CONST;
	const struct param_info_s __param__FW_T_THRO_CONST;
	const struct param_info_s __param__FW_T_THR_DAMP;
	const struct param_info_s __param__FW_T_INTEG_GAIN;
	const struct param_info_s __param__FW_T_VERT_ACC;
	const struct param_info_s __param__FW_T_HGT_OMEGA;
	const struct param_info_s __param__FW_T_SPD_OMEGA;
	const struct param_info_s __param__FW_T_RLL2THR;
	const struct param_info_s __param__FW_T_SPDWEIGHT;
	const struct param_info_s __param__FW_T_PTCH_DAMP;
	const struct param_info_s __param__FW_T_HRATE_P;
	const struct param_info_s __param__FW_T_HRATE_FF;
	const struct param_info_s __param__FW_T_SRATE_P;
	/*****************************************************************
	 * GPS Failure Navigation
	 ****************************************************************/
	const struct param_info_s __param__NAV_GPSF_LT;
	const struct param_info_s __param__NAV_GPSF_R;
	const struct param_info_s __param__NAV_GPSF_P;
	const struct param_info_s __param__NAV_GPSF_TR;
	/*****************************************************************
	 * Geofence
	 ****************************************************************/
	const struct param_info_s __param__GF_ACTION;
	const struct param_info_s __param__GF_ALTMODE;
	const struct param_info_s __param__GF_SOURCE;
	const struct param_info_s __param__GF_COUNT;
	const struct param_info_s __param__GF_MAX_HOR_DIST;
	const struct param_info_s __param__GF_MAX_VER_DIST;
	/*****************************************************************
	 * Gimbal
	 ****************************************************************/
	const struct param_info_s __param__GMB_USE_MNT;
	const struct param_info_s __param__GMB_AUX_MNT_CHN;
	/*****************************************************************
	 * L1 Control
	 ****************************************************************/
	const struct param_info_s __param__FW_L1_PERIOD;
	const struct param_info_s __param__FW_L1_DAMPING;
	const struct param_info_s __param__FW_THR_CRUISE;
	const struct param_info_s __param__FW_THR_SLEW_MAX;
	const struct param_info_s __param__FW_P_LIM_MIN;
	const struct param_info_s __param__FW_P_LIM_MAX;
	const struct param_info_s __param__FW_R_LIM;
	const struct param_info_s __param__FW_THR_MAX;
	const struct param_info_s __param__FW_THR_MIN;
	const struct param_info_s __param__FW_THR_LND_MAX;
	const struct param_info_s __param__FW_CLMBOUT_DIFF;
	const struct param_info_s __param__FW_T_CLMB_MAX;
	const struct param_info_s __param__FW_LND_ANG;
	const struct param_info_s __param__FW_LND_HVIRT;
	const struct param_info_s __param__FW_LND_FLALT;
	const struct param_info_s __param__FW_LND_TLALT;
	const struct param_info_s __param__FW_LND_HHDIST;
	const struct param_info_s __param__FW_LND_USETER;
	const struct param_info_s __param__FW_AIRSPD_SCALE;
	/*****************************************************************
	 * Land Detector
	 ****************************************************************/
	const struct param_info_s __param__LNDMC_Z_VEL_MAX;
	const struct param_info_s __param__LNDMC_XY_VEL_MAX;
	const struct param_info_s __param__LNDMC_ROT_MAX;
	const struct param_info_s __param__LNDMC_THR_MAX;
	const struct param_info_s __param__LNDFW_VEL_XY_MAX;
	const struct param_info_s __param__LNDFW_VEL_Z_MAX;
	const struct param_info_s __param__LNDFW_VELI_MAX;
	const struct param_info_s __param__LNDFW_AIRSPD_MAX;
	/*****************************************************************
	 * Launch detection
	 ****************************************************************/
	const struct param_info_s __param__LAUN_ALL_ON;
	const struct param_info_s __param__LAUN_CAT_A;
	const struct param_info_s __param__LAUN_CAT_T;
	const struct param_info_s __param__LAUN_CAT_MDEL;
	const struct param_info_s __param__LAUN_CAT_PMAX;
	const struct param_info_s __param__LAUN_THR_PRE;
	/*****************************************************************
	 * Linear Velocity L1 Adaptive Control
	 ****************************************************************/
	const struct param_info_s __param__L1V_ACTIVE;
	const struct param_info_s __param__L1V_ENABLE_DEBUG;
	const struct param_info_s __param__L1V_BANDWIDTH_X;
	const struct param_info_s __param__L1V_BANDWIDTH_Y;
	const struct param_info_s __param__L1V_BANDWIDTH_Z;
	const struct param_info_s __param__L1V_OBSERVER_GAIN_X;
	const struct param_info_s __param__L1V_OBSERVER_GAIN_Y;
	const struct param_info_s __param__L1V_OBSERVER_GAIN_Z;
	const struct param_info_s __param__L1V_ADAPTATION_GAIN;
	const struct param_info_s __param__L1V_INIT_DISTX;
	const struct param_info_s __param__L1V_INIT_DISTY;
	const struct param_info_s __param__L1V_INIT_DISTZ;
	const struct param_info_s __param__L1V_ENGAGE_LEVEL;
	/*****************************************************************
	 * Local Position Estimator
	 ****************************************************************/
	const struct param_info_s __param__LPE_ENABLED;
	const struct param_info_s __param__LPE_INTEGRATE;
	const struct param_info_s __param__LPE_FLW_XY;
	const struct param_info_s __param__LPE_SNR_Z;
	const struct param_info_s __param__LPE_LDR_Z;
	const struct param_info_s __param__LPE_ACC_XY;
	const struct param_info_s __param__LPE_ACC_Z;
	const struct param_info_s __param__LPE_BAR_Z;
	const struct param_info_s __param__LPE_GPS_XY;
	const struct param_info_s __param__LPE_GPS_Z;
	const struct param_info_s __param__LPE_GPS_VXY;
	const struct param_info_s __param__LPE_GPS_VZ;
	const struct param_info_s __param__LPE_EPH_MAX;
	const struct param_info_s __param__LPE_VIS_XY;
	const struct param_info_s __param__LPE_VIS_Z;
	const struct param_info_s __param__LPE_NO_VISION;
	const struct param_info_s __param__LPE_VIC_P;
	const struct param_info_s __param__LPE_PN_P;
	const struct param_info_s __param__LPE_PN_V;
	const struct param_info_s __param__LPE_PN_B;
	const struct param_info_s __param__LPE_BETA_MAX;
	/*****************************************************************
	 * MAVLink
	 ****************************************************************/
	const struct param_info_s __param__MAV_BASE_ID;
	const struct param_info_s __param__MAV_SYS_ID;
	const struct param_info_s __param__MAV_COMP_ID;
	const struct param_info_s __param__MAV_RADIO_ID;
	const struct param_info_s __param__MAV_TYPE;
	const struct param_info_s __param__MAV_USEHILGPS;
	const struct param_info_s __param__MAV_FWDEXTSP;
	const struct param_info_s __param__MAV_TEST_PAR;
	/*****************************************************************
	 * MKBLCTRL Testmode
	 ****************************************************************/
	const struct param_info_s __param__MKBLCTRL_TEST;
	/*****************************************************************
	 * Mission
	 ****************************************************************/
	const struct param_info_s __param__NAV_LOITER_RAD;
	const struct param_info_s __param__NAV_ACC_RAD;
	const struct param_info_s __param__NAV_DLL_OBC;
	const struct param_info_s __param__NAV_RCL_OBC;
	const struct param_info_s __param__MIS_TAKEOFF_ALT;
	const struct param_info_s __param__MIS_ONBOARD_EN;
	const struct param_info_s __param__MIS_DIST_1WP;
	const struct param_info_s __param__MIS_ALTMODE;
	const struct param_info_s __param__MIS_YAWMODE;
	/*****************************************************************
	 * Multicopter Attitude Control
	 ****************************************************************/
	const struct param_info_s __param__MPP_MAN_R_MAX;
	const struct param_info_s __param__MPP_MAN_P_MAX;
	const struct param_info_s __param__MPP_MAN_Y_MAX;
	const struct param_info_s __param__MP_ROLL_P;
	const struct param_info_s __param__MP_ROLLRATE_P;
	const struct param_info_s __param__MP_ROLLRATE_I;
	const struct param_info_s __param__MP_ROLLRATE_D;
	const struct param_info_s __param__MP_PITCH_P;
	const struct param_info_s __param__MP_PITCHRATE_P;
	const struct param_info_s __param__MP_PITCHRATE_I;
	const struct param_info_s __param__MP_PITCHRATE_D;
	const struct param_info_s __param__MP_YAW_P;
	const struct param_info_s __param__MP_YAWRATE_P;
	const struct param_info_s __param__MP_YAWRATE_I;
	const struct param_info_s __param__MP_YAWRATE_D;
	const struct param_info_s __param__MP_YAW_FF;
	const struct param_info_s __param__MP_YAWRATE_MAX;
	const struct param_info_s __param__MP_ACRO_R_MAX;
	const struct param_info_s __param__MP_ACRO_P_MAX;
	const struct param_info_s __param__MP_ACRO_Y_MAX;
	const struct param_info_s __param__MC_ROLL_TC;
	const struct param_info_s __param__MC_PITCH_TC;
	const struct param_info_s __param__MC_ROLL_P;
	const struct param_info_s __param__MC_ROLLRATE_P;
	const struct param_info_s __param__MC_ROLLRATE_I;
	const struct param_info_s __param__MC_ROLLRATE_D;
	const struct param_info_s __param__MC_ROLLRATE_FF;
	const struct param_info_s __param__MC_PITCH_P;
	const struct param_info_s __param__MC_PITCHRATE_P;
	const struct param_info_s __param__MC_PITCHRATE_I;
	const struct param_info_s __param__MC_PITCHRATE_D;
	const struct param_info_s __param__MC_PITCHRATE_FF;
	const struct param_info_s __param__MC_YAW_P;
	const struct param_info_s __param__MC_YAWRATE_P;
	const struct param_info_s __param__MC_YAWRATE_I;
	const struct param_info_s __param__MC_YAWRATE_D;
	const struct param_info_s __param__MC_YAWRATE_FF;
	const struct param_info_s __param__MC_YAW_FF;
	const struct param_info_s __param__MC_ROLLRATE_MAX;
	const struct param_info_s __param__MC_PITCHRATE_MAX;
	const struct param_info_s __param__MC_YAWRATE_MAX;
	const struct param_info_s __param__MC_ACRO_R_MAX;
	const struct param_info_s __param__MC_ACRO_P_MAX;
	const struct param_info_s __param__MC_ACRO_Y_MAX;
	const struct param_info_s __param__MC_RATT_TH;
	/*****************************************************************
	 * Multicopter Position Control
	 ****************************************************************/
	const struct param_info_s __param__MPP_THR_MIN;
	const struct param_info_s __param__MPP_THR_MAX;
	const struct param_info_s __param__MPP_Z_P;
	const struct param_info_s __param__MPP_Z_VEL_P;
	const struct param_info_s __param__MPP_Z_VEL_I;
	const struct param_info_s __param__MPP_Z_VEL_D;
	const struct param_info_s __param__MPP_Z_VEL_MAX;
	const struct param_info_s __param__MPP_Z_FF;
	const struct param_info_s __param__MPP_XY_P;
	const struct param_info_s __param__MPP_XY_VEL_P;
	const struct param_info_s __param__MPP_XY_VEL_I;
	const struct param_info_s __param__MPP_XY_VEL_D;
	const struct param_info_s __param__MPP_XY_VEL_MAX;
	const struct param_info_s __param__MPP_XY_FF;
	const struct param_info_s __param__MPP_TILTMAX_AIR;
	const struct param_info_s __param__MPP_TILTMAX_LND;
	const struct param_info_s __param__MPP_LAND_SPEED;
	const struct param_info_s __param__MPC_THR_MIN;
	const struct param_info_s __param__MPC_THR_MAX;
	const struct param_info_s __param__MPC_MANTHR_MIN;
	const struct param_info_s __param__MPC_MANTHR_MAX;
	const struct param_info_s __param__MPC_Z_P;
	const struct param_info_s __param__MPC_Z_VEL_P;
	const struct param_info_s __param__MPC_Z_VEL_I;
	const struct param_info_s __param__MPC_Z_VEL_D;
	const struct param_info_s __param__MPC_Z_VEL_MAX;
	const struct param_info_s __param__MPC_Z_FF;
	const struct param_info_s __param__MPC_XY_P;
	const struct param_info_s __param__MPC_XY_VEL_P;
	const struct param_info_s __param__MPC_XY_VEL_I;
	const struct param_info_s __param__MPC_XY_VEL_D;
	const struct param_info_s __param__MPC_XY_VEL_MAX;
	const struct param_info_s __param__MPC_XY_FF;
	const struct param_info_s __param__MPC_TILTMAX_AIR;
	const struct param_info_s __param__MPC_TILTMAX_LND;
	const struct param_info_s __param__MPC_LAND_SPEED;
	const struct param_info_s __param__MPC_TKO_SPEED;
	const struct param_info_s __param__MPC_MAN_R_MAX;
	const struct param_info_s __param__MPC_MAN_P_MAX;
	const struct param_info_s __param__MPC_MAN_Y_MAX;
	const struct param_info_s __param__MPC_HOLD_XY_DZ;
	const struct param_info_s __param__MPC_HOLD_Z_DZ;
	const struct param_info_s __param__MPC_HOLD_MAX_XY;
	const struct param_info_s __param__MPC_HOLD_MAX_Z;
	const struct param_info_s __param__MPC_VELD_LP;
	const struct param_info_s __param__MPC_ACC_HOR_MAX;
	const struct param_info_s __param__MPC_USE_GRAV_FF;
	const struct param_info_s __param__MPC_TKOFF_VZSP;
	/*****************************************************************
	 * Multicoptor Attitude Control
	 ****************************************************************/
	const struct param_info_s __param__MC_ENABLE_L1A;
	/*****************************************************************
	 * Multicoptor Position Control
	 ****************************************************************/
	const struct param_info_s __param__MPC_ENABLE_L1V;
	/*****************************************************************
	 * PWM Outputs
	 ****************************************************************/
	const struct param_info_s __param__PWM_AUX_REV1;
	const struct param_info_s __param__PWM_AUX_REV2;
	const struct param_info_s __param__PWM_AUX_REV3;
	const struct param_info_s __param__PWM_AUX_REV4;
	const struct param_info_s __param__PWM_AUX_REV5;
	const struct param_info_s __param__PWM_AUX_REV6;
	const struct param_info_s __param__PWM_MAIN_REV1;
	const struct param_info_s __param__PWM_MAIN_REV2;
	const struct param_info_s __param__PWM_MAIN_REV3;
	const struct param_info_s __param__PWM_MAIN_REV4;
	const struct param_info_s __param__PWM_MAIN_REV5;
	const struct param_info_s __param__PWM_MAIN_REV6;
	const struct param_info_s __param__PWM_MAIN_REV7;
	const struct param_info_s __param__PWM_MAIN_REV8;
	const struct param_info_s __param__PWM_SBUS_MODE;
	const struct param_info_s __param__PWM_MIN;
	const struct param_info_s __param__PWM_MAX;
	const struct param_info_s __param__PWM_DISARMED;
	const struct param_info_s __param__PWM_AUX_MIN;
	const struct param_info_s __param__PWM_AUX_MAX;
	const struct param_info_s __param__PWM_AUX_DISARMED;
	/*****************************************************************
	 * Payload drop
	 ****************************************************************/
	const struct param_info_s __param__BD_GPROPERTIES;
	const struct param_info_s __param__BD_TURNRADIUS;
	const struct param_info_s __param__BD_PRECISION;
	const struct param_info_s __param__BD_OBJ_CD;
	const struct param_info_s __param__BD_OBJ_MASS;
	const struct param_info_s __param__BD_OBJ_SURFACE;
	/*****************************************************************
	 * Physics
	 ****************************************************************/
	const struct param_info_s __param__PHY_RPM_PER_PWM;
	const struct param_info_s __param__PHY_RPM_PER_VOLT;
	const struct param_info_s __param__PHY_RPM_AT_ZERO_PWM_AND_VOLTS;
	const struct param_info_s __param__PHY_INERTIA_XX;
	const struct param_info_s __param__PHY_INERTIA_XY;
	const struct param_info_s __param__PHY_INERTIA_XZ;
	const struct param_info_s __param__PHY_INERTIA_YY;
	const struct param_info_s __param__PHY_INERTIA_YZ;
	const struct param_info_s __param__PHY_INERTIA_ZZ;
	const struct param_info_s __param__PHY_CT;
	const struct param_info_s __param__PHY_MOTOR_CONSTANT;
	const struct param_info_s __param__PHY_ARM_LENGTH;
	const struct param_info_s __param__PHY_MOMENT_SCALE;
	const struct param_info_s __param__PHY_MOTOR_SPREAD_ANGLE;
	const struct param_info_s __param__PHY_RPM_MIN;
	const struct param_info_s __param__PHY_RPM_MAX;
	const struct param_info_s __param__PHY_VOLTAGE_MAX;
	const struct param_info_s __param__PHY_TOTAL_MASS;
	const struct param_info_s __param__PHY_GRAVITY;
	/*****************************************************************
	 * Position Estimator
	 ****************************************************************/
	const struct param_info_s __param__PE_VEL_DELAY_MS;
	const struct param_info_s __param__PE_POS_DELAY_MS;
	const struct param_info_s __param__PE_HGT_DELAY_MS;
	const struct param_info_s __param__PE_MAG_DELAY_MS;
	const struct param_info_s __param__PE_TAS_DELAY_MS;
	const struct param_info_s __param__PE_GPS_ALT_WGT;
	const struct param_info_s __param__PE_EAS_NOISE;
	const struct param_info_s __param__PE_VELNE_NOISE;
	const struct param_info_s __param__PE_VELD_NOISE;
	const struct param_info_s __param__PE_POSNE_NOISE;
	const struct param_info_s __param__PE_POSD_NOISE;
	const struct param_info_s __param__PE_MAG_NOISE;
	const struct param_info_s __param__PE_GYRO_PNOISE;
	const struct param_info_s __param__PE_ACC_PNOISE;
	const struct param_info_s __param__PE_GBIAS_PNOISE;
	const struct param_info_s __param__PE_ABIAS_PNOISE;
	const struct param_info_s __param__PE_MAGE_PNOISE;
	const struct param_info_s __param__PE_MAGB_PNOISE;
	const struct param_info_s __param__PE_MAGB_X;
	const struct param_info_s __param__PE_MAGB_Y;
	const struct param_info_s __param__PE_MAGB_Z;
	const struct param_info_s __param__PE_POSDEV_INIT;
	/*****************************************************************
	 * Position Estimator INAV
	 ****************************************************************/
	const struct param_info_s __param__INAV_W_Z_BARO;
	const struct param_info_s __param__INAV_W_Z_GPS_P;
	const struct param_info_s __param__INAV_W_Z_GPS_V;
	const struct param_info_s __param__INAV_W_Z_VIS_P;
	const struct param_info_s __param__INAV_W_Z_LIDAR;
	const struct param_info_s __param__INAV_W_XY_GPS_P;
	const struct param_info_s __param__INAV_W_XY_GPS_V;
	const struct param_info_s __param__INAV_W_XY_VIS_P;
	const struct param_info_s __param__INAV_W_XY_VIS_V;
	const struct param_info_s __param__INAV_W_MOC_P;
	const struct param_info_s __param__INAV_W_XY_FLOW;
	const struct param_info_s __param__INAV_W_XY_RES_V;
	const struct param_info_s __param__INAV_W_GPS_FLOW;
	const struct param_info_s __param__INAV_W_ACC_BIAS;
	const struct param_info_s __param__INAV_FLOW_K;
	const struct param_info_s __param__INAV_FLOW_Q_MIN;
	const struct param_info_s __param__INAV_LIDAR_FILT;
	const struct param_info_s __param__INAV_LIDAR_ERR;
	const struct param_info_s __param__INAV_LAND_T;
	const struct param_info_s __param__INAV_LAND_DISP;
	const struct param_info_s __param__INAV_LAND_THR;
	const struct param_info_s __param__INAV_DELAY_GPS;
	const struct param_info_s __param__INAV_FLOW_DIST_X;
	const struct param_info_s __param__INAV_FLOW_DIST_Y;
	const struct param_info_s __param__INAV_DISAB_MOCAP;
	const struct param_info_s __param__CBRK_NO_VISION;
	const struct param_info_s __param__INAV_ENABLED;
	/*****************************************************************
	 * Radio Calibration
	 ****************************************************************/
	const struct param_info_s __param__TRIM_ROLL;
	const struct param_info_s __param__TRIM_PITCH;
	const struct param_info_s __param__TRIM_YAW;
	const struct param_info_s __param__RC1_MIN;
	const struct param_info_s __param__RC1_TRIM;
	const struct param_info_s __param__RC1_MAX;
	const struct param_info_s __param__RC1_REV;
	const struct param_info_s __param__RC1_DZ;
	const struct param_info_s __param__RC2_MIN;
	const struct param_info_s __param__RC2_TRIM;
	const struct param_info_s __param__RC2_MAX;
	const struct param_info_s __param__RC2_REV;
	const struct param_info_s __param__RC2_DZ;
	const struct param_info_s __param__RC3_MIN;
	const struct param_info_s __param__RC3_TRIM;
	const struct param_info_s __param__RC3_MAX;
	const struct param_info_s __param__RC3_REV;
	const struct param_info_s __param__RC3_DZ;
	const struct param_info_s __param__RC4_MIN;
	const struct param_info_s __param__RC4_TRIM;
	const struct param_info_s __param__RC4_MAX;
	const struct param_info_s __param__RC4_REV;
	const struct param_info_s __param__RC4_DZ;
	const struct param_info_s __param__RC5_MIN;
	const struct param_info_s __param__RC5_TRIM;
	const struct param_info_s __param__RC5_MAX;
	const struct param_info_s __param__RC5_REV;
	const struct param_info_s __param__RC5_DZ;
	const struct param_info_s __param__RC6_MIN;
	const struct param_info_s __param__RC6_TRIM;
	const struct param_info_s __param__RC6_MAX;
	const struct param_info_s __param__RC6_REV;
	const struct param_info_s __param__RC6_DZ;
	const struct param_info_s __param__RC7_MIN;
	const struct param_info_s __param__RC7_TRIM;
	const struct param_info_s __param__RC7_MAX;
	const struct param_info_s __param__RC7_REV;
	const struct param_info_s __param__RC7_DZ;
	const struct param_info_s __param__RC8_MIN;
	const struct param_info_s __param__RC8_TRIM;
	const struct param_info_s __param__RC8_MAX;
	const struct param_info_s __param__RC8_REV;
	const struct param_info_s __param__RC8_DZ;
	const struct param_info_s __param__RC9_MIN;
	const struct param_info_s __param__RC9_TRIM;
	const struct param_info_s __param__RC9_MAX;
	const struct param_info_s __param__RC9_REV;
	const struct param_info_s __param__RC9_DZ;
	const struct param_info_s __param__RC10_MIN;
	const struct param_info_s __param__RC10_TRIM;
	const struct param_info_s __param__RC10_MAX;
	const struct param_info_s __param__RC10_REV;
	const struct param_info_s __param__RC10_DZ;
	const struct param_info_s __param__RC11_MIN;
	const struct param_info_s __param__RC11_TRIM;
	const struct param_info_s __param__RC11_MAX;
	const struct param_info_s __param__RC11_REV;
	const struct param_info_s __param__RC11_DZ;
	const struct param_info_s __param__RC12_MIN;
	const struct param_info_s __param__RC12_TRIM;
	const struct param_info_s __param__RC12_MAX;
	const struct param_info_s __param__RC12_REV;
	const struct param_info_s __param__RC12_DZ;
	const struct param_info_s __param__RC13_MIN;
	const struct param_info_s __param__RC13_TRIM;
	const struct param_info_s __param__RC13_MAX;
	const struct param_info_s __param__RC13_REV;
	const struct param_info_s __param__RC13_DZ;
	const struct param_info_s __param__RC14_MIN;
	const struct param_info_s __param__RC14_TRIM;
	const struct param_info_s __param__RC14_MAX;
	const struct param_info_s __param__RC14_REV;
	const struct param_info_s __param__RC14_DZ;
	const struct param_info_s __param__RC15_MIN;
	const struct param_info_s __param__RC15_TRIM;
	const struct param_info_s __param__RC15_MAX;
	const struct param_info_s __param__RC15_REV;
	const struct param_info_s __param__RC15_DZ;
	const struct param_info_s __param__RC16_MIN;
	const struct param_info_s __param__RC16_TRIM;
	const struct param_info_s __param__RC16_MAX;
	const struct param_info_s __param__RC16_REV;
	const struct param_info_s __param__RC16_DZ;
	const struct param_info_s __param__RC17_MIN;
	const struct param_info_s __param__RC17_TRIM;
	const struct param_info_s __param__RC17_MAX;
	const struct param_info_s __param__RC17_REV;
	const struct param_info_s __param__RC17_DZ;
	const struct param_info_s __param__RC18_MIN;
	const struct param_info_s __param__RC18_TRIM;
	const struct param_info_s __param__RC18_MAX;
	const struct param_info_s __param__RC18_REV;
	const struct param_info_s __param__RC18_DZ;
	const struct param_info_s __param__RC_RL1_DSM_VCC;
	const struct param_info_s __param__RC_DSM_BIND;
	const struct param_info_s __param__RC_CHAN_CNT;
	const struct param_info_s __param__RC_TH_USER;
	const struct param_info_s __param__RC_MAP_ROLL;
	const struct param_info_s __param__RC_MAP_PITCH;
	const struct param_info_s __param__RC_MAP_THROTTLE;
	const struct param_info_s __param__RC_MAP_YAW;
	const struct param_info_s __param__RC_MAP_AUX1;
	const struct param_info_s __param__RC_MAP_AUX2;
	const struct param_info_s __param__RC_MAP_AUX3;
	const struct param_info_s __param__RC_MAP_PARAM1;
	const struct param_info_s __param__RC_MAP_PARAM2;
	const struct param_info_s __param__RC_MAP_PARAM3;
	const struct param_info_s __param__RC_FAILS_THR;
	const struct param_info_s __param__RC_RSSI_PWM_CHAN;
	const struct param_info_s __param__RC_RSSI_PWM_MAX;
	const struct param_info_s __param__RC_RSSI_PWM_MIN;
	/*****************************************************************
	 * Radio Signal Loss
	 ****************************************************************/
	const struct param_info_s __param__NAV_RCL_LT;
	/*****************************************************************
	 * Radio Switches
	 ****************************************************************/
	const struct param_info_s __param__RC_MAP_MODE_SW;
	const struct param_info_s __param__RC_MAP_RETURN_SW;
	const struct param_info_s __param__RC_MAP_RATT_SW;
	const struct param_info_s __param__RC_MAP_POSCTL_SW;
	const struct param_info_s __param__RC_MAP_LOITER_SW;
	const struct param_info_s __param__RC_MAP_ACRO_SW;
	const struct param_info_s __param__RC_MAP_OFFB_SW;
	const struct param_info_s __param__RC_MAP_KILL_SW;
	const struct param_info_s __param__RC_MAP_FLAPS;
	const struct param_info_s __param__RC_ASSIST_TH;
	const struct param_info_s __param__RC_AUTO_TH;
	const struct param_info_s __param__RC_RATT_TH;
	const struct param_info_s __param__RC_POSCTL_TH;
	const struct param_info_s __param__RC_RETURN_TH;
	const struct param_info_s __param__RC_LOITER_TH;
	const struct param_info_s __param__RC_ACRO_TH;
	const struct param_info_s __param__RC_OFFB_TH;
	const struct param_info_s __param__RC_KILLSWITCH_TH;
	/*****************************************************************
	 * Return To Land
	 ****************************************************************/
	const struct param_info_s __param__RTL_RETURN_ALT;
	const struct param_info_s __param__RTL_DESCEND_ALT;
	const struct param_info_s __param__RTL_LAND_DELAY;
	/*****************************************************************
	 * Runway Takeoff
	 ****************************************************************/
	const struct param_info_s __param__RWTO_TKOFF;
	const struct param_info_s __param__RWTO_HDG;
	const struct param_info_s __param__RWTO_NAV_ALT;
	const struct param_info_s __param__RWTO_MAX_THR;
	const struct param_info_s __param__RWTO_PSP;
	const struct param_info_s __param__RWTO_MAX_PITCH;
	const struct param_info_s __param__RWTO_MAX_ROLL;
	const struct param_info_s __param__RWTO_AIRSPD_SCL;
	/*****************************************************************
	 * SD Logging
	 ****************************************************************/
	const struct param_info_s __param__SDLOG_RATE;
	const struct param_info_s __param__SDLOG_EXT;
	const struct param_info_s __param__SDLOG_GPSTIME;
	/*****************************************************************
	 * Sensor Calibration
	 ****************************************************************/
	const struct param_info_s __param__CAL_BOARD_ID;
	const struct param_info_s __param__CAL_GYRO0_ID;
	const struct param_info_s __param__CAL_GYRO0_XOFF;
	const struct param_info_s __param__CAL_GYRO0_YOFF;
	const struct param_info_s __param__CAL_GYRO0_ZOFF;
	const struct param_info_s __param__CAL_GYRO0_XSCALE;
	const struct param_info_s __param__CAL_GYRO0_YSCALE;
	const struct param_info_s __param__CAL_GYRO0_ZSCALE;
	const struct param_info_s __param__CAL_MAG0_ID;
	const struct param_info_s __param__CAL_MAG0_ROT;
	const struct param_info_s __param__CAL_MAG0_XOFF;
	const struct param_info_s __param__CAL_MAG0_YOFF;
	const struct param_info_s __param__CAL_MAG0_ZOFF;
	const struct param_info_s __param__CAL_MAG0_XSCALE;
	const struct param_info_s __param__CAL_MAG0_YSCALE;
	const struct param_info_s __param__CAL_MAG0_ZSCALE;
	const struct param_info_s __param__CAL_ACC0_ID;
	const struct param_info_s __param__CAL_ACC0_XOFF;
	const struct param_info_s __param__CAL_ACC0_YOFF;
	const struct param_info_s __param__CAL_ACC0_ZOFF;
	const struct param_info_s __param__CAL_ACC0_XSCALE;
	const struct param_info_s __param__CAL_ACC0_YSCALE;
	const struct param_info_s __param__CAL_ACC0_ZSCALE;
	const struct param_info_s __param__CAL_GYRO1_ID;
	const struct param_info_s __param__CAL_GYRO1_XOFF;
	const struct param_info_s __param__CAL_GYRO1_YOFF;
	const struct param_info_s __param__CAL_GYRO1_ZOFF;
	const struct param_info_s __param__CAL_GYRO1_XSCALE;
	const struct param_info_s __param__CAL_GYRO1_YSCALE;
	const struct param_info_s __param__CAL_GYRO1_ZSCALE;
	const struct param_info_s __param__CAL_MAG1_ID;
	const struct param_info_s __param__CAL_MAG1_ROT;
	const struct param_info_s __param__CAL_MAG1_XOFF;
	const struct param_info_s __param__CAL_MAG1_YOFF;
	const struct param_info_s __param__CAL_MAG1_ZOFF;
	const struct param_info_s __param__CAL_MAG1_XSCALE;
	const struct param_info_s __param__CAL_MAG1_YSCALE;
	const struct param_info_s __param__CAL_MAG1_ZSCALE;
	const struct param_info_s __param__CAL_ACC1_ID;
	const struct param_info_s __param__CAL_ACC1_XOFF;
	const struct param_info_s __param__CAL_ACC1_YOFF;
	const struct param_info_s __param__CAL_ACC1_ZOFF;
	const struct param_info_s __param__CAL_ACC1_XSCALE;
	const struct param_info_s __param__CAL_ACC1_YSCALE;
	const struct param_info_s __param__CAL_ACC1_ZSCALE;
	const struct param_info_s __param__CAL_GYRO2_ID;
	const struct param_info_s __param__CAL_GYRO2_XOFF;
	const struct param_info_s __param__CAL_GYRO2_YOFF;
	const struct param_info_s __param__CAL_GYRO2_ZOFF;
	const struct param_info_s __param__CAL_GYRO2_XSCALE;
	const struct param_info_s __param__CAL_GYRO2_YSCALE;
	const struct param_info_s __param__CAL_GYRO2_ZSCALE;
	const struct param_info_s __param__CAL_MAG2_ID;
	const struct param_info_s __param__CAL_MAG2_ROT;
	const struct param_info_s __param__CAL_MAG2_XOFF;
	const struct param_info_s __param__CAL_MAG2_YOFF;
	const struct param_info_s __param__CAL_MAG2_ZOFF;
	const struct param_info_s __param__CAL_MAG2_XSCALE;
	const struct param_info_s __param__CAL_MAG2_YSCALE;
	const struct param_info_s __param__CAL_MAG2_ZSCALE;
	const struct param_info_s __param__CAL_ACC2_ID;
	const struct param_info_s __param__CAL_ACC2_XOFF;
	const struct param_info_s __param__CAL_ACC2_YOFF;
	const struct param_info_s __param__CAL_ACC2_ZOFF;
	const struct param_info_s __param__CAL_ACC2_XSCALE;
	const struct param_info_s __param__CAL_ACC2_YSCALE;
	const struct param_info_s __param__CAL_ACC2_ZSCALE;
	const struct param_info_s __param__CAL_ACC_PRIME;
	const struct param_info_s __param__CAL_GYRO_PRIME;
	const struct param_info_s __param__CAL_MAG_PRIME;
	const struct param_info_s __param__CAL_BARO_PRIME;
	const struct param_info_s __param__SENS_DPRES_OFF;
	const struct param_info_s __param__SENS_DPRES_ANSC;
	const struct param_info_s __param__SENS_BARO_QNH;
	const struct param_info_s __param__SENS_BOARD_ROT;
	const struct param_info_s __param__SENS_FLOW_ROT;
	const struct param_info_s __param__SENS_BOARD_Y_OFF;
	const struct param_info_s __param__SENS_BOARD_X_OFF;
	const struct param_info_s __param__SENS_BOARD_Z_OFF;
	const struct param_info_s __param__SENS_FLOW_X_OFF;
	const struct param_info_s __param__SENS_FLOW_Y_OFF;
	const struct param_info_s __param__SENS_EXT_MAG_ROT;
	const struct param_info_s __param__SENS_EXT_MAG;
	/*****************************************************************
	 * Sensor Enable
	 ****************************************************************/
	const struct param_info_s __param__SENS_EN_LL40LS;
	/*****************************************************************
	 * Subscriber Example
	 ****************************************************************/
	const struct param_info_s __param__SUB_INTERV;
	const struct param_info_s __param__SUB_TESTF;
	/*****************************************************************
	 * System
	 ****************************************************************/
	const struct param_info_s __param__SYS_AUTOSTART;
	const struct param_info_s __param__SYS_AUTOCONFIG;
	const struct param_info_s __param__SYS_USE_IO;
	const struct param_info_s __param__SYS_RESTART_TYPE;
	const struct param_info_s __param__SYS_COMPANION;
	const struct param_info_s __param__SYS_PARAM_VER;
	/*****************************************************************
	 * UAVCAN
	 ****************************************************************/
	const struct param_info_s __param__UAVCAN_ENABLE;
	const struct param_info_s __param__UAVCAN_NODE_ID;
	const struct param_info_s __param__UAVCAN_BITRATE;
	/*****************************************************************
	 * VTOL Attitude Control
	 ****************************************************************/
	const struct param_info_s __param__VT_TILT_MC;
	const struct param_info_s __param__VT_TILT_TRANS;
	const struct param_info_s __param__VT_TILT_FW;
	const struct param_info_s __param__VT_TRANS_P2_DUR;
	const struct param_info_s __param__VT_FW_MOT_OFFID;
	const struct param_info_s __param__VT_TRANS_THR;
	const struct param_info_s __param__VT_MOT_COUNT;
	const struct param_info_s __param__VT_IDLE_PWM_MC;
	const struct param_info_s __param__VT_MC_ARSPD_MIN;
	const struct param_info_s __param__VT_MC_ARSPD_MAX;
	const struct param_info_s __param__VT_MC_ARSPD_TRIM;
	const struct param_info_s __param__VT_FW_PERM_STAB;
	const struct param_info_s __param__VT_FW_PITCH_TRIM;
	const struct param_info_s __param__VT_POWER_MAX;
	const struct param_info_s __param__VT_PROP_EFF;
	const struct param_info_s __param__VT_ARSP_LP_GAIN;
	const struct param_info_s __param__VT_TYPE;
	const struct param_info_s __param__VT_ELEV_MC_LOCK;
	const struct param_info_s __param__VT_F_TRANS_DUR;
	const struct param_info_s __param__VT_B_TRANS_DUR;
	const struct param_info_s __param__VT_ARSP_BLEND;
	const struct param_info_s __param__VT_ARSP_TRANS;
	const struct param_info_s __param__VT_OPT_RECOV_EN;
	/*****************************************************************
	 * mTECS
	 ****************************************************************/
	const struct param_info_s __param__MT_ENABLED;
	const struct param_info_s __param__MT_THR_FF;
	const struct param_info_s __param__MT_THR_P;
	const struct param_info_s __param__MT_THR_I;
	const struct param_info_s __param__MT_THR_OFF;
	const struct param_info_s __param__MT_PIT_FF;
	const struct param_info_s __param__MT_PIT_P;
	const struct param_info_s __param__MT_PIT_I;
	const struct param_info_s __param__MT_PIT_OFF;
	const struct param_info_s __param__MT_THR_MIN;
	const struct param_info_s __param__MT_THR_MAX;
	const struct param_info_s __param__MT_PIT_MIN;
	const struct param_info_s __param__MT_PIT_MAX;
	const struct param_info_s __param__MT_ALT_LP;
	const struct param_info_s __param__MT_FPA_LP;
	const struct param_info_s __param__MT_FPA_P;
	const struct param_info_s __param__MT_FPA_D;
	const struct param_info_s __param__MT_FPA_D_LP;
	const struct param_info_s __param__MT_FPA_MIN;
	const struct param_info_s __param__MT_FPA_MAX;
	const struct param_info_s __param__MT_A_LP;
	const struct param_info_s __param__MT_AD_LP;
	const struct param_info_s __param__MT_ACC_P;
	const struct param_info_s __param__MT_ACC_D;
	const struct param_info_s __param__MT_ACC_D_LP;
	const struct param_info_s __param__MT_ACC_MIN;
	const struct param_info_s __param__MT_ACC_MAX;
	const struct param_info_s __param__MT_TKF_THR_MIN;
	const struct param_info_s __param__MT_TKF_THR_MAX;
	const struct param_info_s __param__MT_TKF_PIT_MIN;
	const struct param_info_s __param__MT_TKF_PIT_MAX;
	const struct param_info_s __param__MT_USP_THR_MIN;
	const struct param_info_s __param__MT_USP_THR_MAX;
	const struct param_info_s __param__MT_USP_PIT_MIN;
	const struct param_info_s __param__MT_USP_PIT_MAX;
	const struct param_info_s __param__MT_LND_THR_MIN;
	const struct param_info_s __param__MT_LND_THR_MAX;
	const struct param_info_s __param__MT_LND_PIT_MIN;
	const struct param_info_s __param__MT_LND_PIT_MAX;
	const struct param_info_s __param__MT_THR_I_MAX;
	const struct param_info_s __param__MT_PIT_I_MAX;
	/*****************************************************************
	 * Miscellaneous
	 ****************************************************************/
	const struct param_info_s __param__LED_RGB_MAXBRT;
	const struct param_info_s __param__MSM_INTENSITY;
	const struct param_info_s __param__SEG_TH2V_P;
	const struct param_info_s __param__SEG_TH2V_I;
	const struct param_info_s __param__SEG_TH2V_I_MAX;
	const struct param_info_s __param__SEG_Q2V;
	const struct param_info_s __param__MSM_IGN_THRESH;
	const struct param_info_s __param__MSM_LOW_THRESH;
	const struct param_info_s __param__MSM_CRIT_THRESH;
	const struct param_info_s __param__TEST_MIN;
	const struct param_info_s __param__TEST_MAX;
	const struct param_info_s __param__TEST_TRIM;
	const struct param_info_s __param__TEST_HP;
	const struct param_info_s __param__TEST_LP;
	const struct param_info_s __param__TEST_P;
	const struct param_info_s __param__TEST_I;
	const struct param_info_s __param__TEST_I_MAX;
	const struct param_info_s __param__TEST_D;
	const struct param_info_s __param__TEST_D_LP;
	const struct param_info_s __param__TEST_MEAN;
	const struct param_info_s __param__TEST_DEV;
	const struct param_info_s __param__MCC_RPM_MIN;
	const struct param_info_s __param__MCC_RPM_START;
	const struct param_info_s __param__MCC_RPM_MAX;
	const struct param_info_s __param__MCC_CT;
	const struct param_info_s __param__MCC_MOMENT_SCALE;
	const struct param_info_s __param__MCC_ARM_LENGTH;
	const struct param_info_s __param__MCC_TOTAL_MASS;
	const struct param_info_s __param__MCC_MOTOR_SPREAD;
	const struct param_info_s __param__MCC_INERTIA_XX;
	const struct param_info_s __param__MCC_INERTIA_XY;
	const struct param_info_s __param__MCC_INERTIA_XZ;
	const struct param_info_s __param__MCC_INERTIA_YY;
	const struct param_info_s __param__MCC_INERTIA_YZ;
	const struct param_info_s __param__MCC_INERTIA_ZZ;
	const struct param_info_s __param__MCC_GRAVITY;
	const struct param_info_s __param__MCC_MOT_START_DT;
	const struct param_info_s __param__MCC_MOTOR_CONST;
	const struct param_info_s __param__MCC_CMD_TTL;
	const struct param_info_s __param__MCC_PWM_MAP1;
	const struct param_info_s __param__MCC_PWM_MAP2;
	const struct param_info_s __param__MCC_PWM_MAP3;
	const struct param_info_s __param__MCC_PWM_MAP4;
	const struct param_info_s __param__MCC_PWM_RATE;
	const struct param_info_s __param__MCC_RPM2PWM_00;
	const struct param_info_s __param__MCC_RPM2PWM_10;
	const struct param_info_s __param__MCC_RPM2PWM_01;
	const struct param_info_s __param__MCC_RPM2PWM_20;
	const struct param_info_s __param__MCC_RPM2PWM_11;
	const struct param_info_s __param__MCC_RPM2PWM_02;
	const struct param_info_s __param__MCC_RPM2PWM_30;
	const struct param_info_s __param__MCC_RPM2PWM_21;
	const struct param_info_s __param__MCC_RPM2PWM_12;
	const struct param_info_s __param__MCC_RPM2PWM_03;
	const struct param_info_s __param__MCC_RPM2PWM_40;
	const struct param_info_s __param__MCC_RPM2PWM_31;
	const struct param_info_s __param__MCC_RPM2PWM_22;
	const struct param_info_s __param__MCC_RPM2PWM_13;
	const struct param_info_s __param__MCC_RPM2PWM_04;
	const struct param_info_s __param__MCC_RPM2PWM_50;
	const struct param_info_s __param__MCC_RPM2PWM_41;
	const struct param_info_s __param__MCC_RPM2PWM_32;
	const struct param_info_s __param__MCC_RPM2PWM_23;
	const struct param_info_s __param__MCC_RPM2PWM_14;
	const struct param_info_s __param__MCC_RPM2PWM_05;
	const struct param_info_s __param__MCC_RPM_M;
	const struct param_info_s __param__MCC_RPM_SD;
	const struct param_info_s __param__MCC_V_M;
	const struct param_info_s __param__MCC_V_SD;
	const struct param_info_s __param__MCC_ENABLE_L1C;
	const struct param_info_s __param__L1C_ACTIVE;
	const struct param_info_s __param__L1C_BW_X;
	const struct param_info_s __param__L1C_BW_Y;
	const struct param_info_s __param__L1C_BW_Z;
	const struct param_info_s __param__L1C_OBS_GAIN_X;
	const struct param_info_s __param__L1C_OBS_GAIN_Y;
	const struct param_info_s __param__L1C_OBS_GAIN_Z;
	const struct param_info_s __param__L1C_ADAPT_GAIN_X;
	const struct param_info_s __param__L1C_ADAPT_GAIN_Y;
	const struct param_info_s __param__L1C_ADAPT_GAIN_Z;
	const struct param_info_s __param__L1C_INIT_DIST_X;
	const struct param_info_s __param__L1C_INIT_DIST_Y;
	const struct param_info_s __param__L1C_INIT_DIST_Z;
	const struct param_info_s __param__L1C_ENGAGE_LEVEL;
	const struct param_info_s __param__L1C_ENABLE_DEBUG;
	const struct param_info_s __param__MCC_ENABLE_L1P;
	const struct param_info_s __param__L1P_ACTIVE;
	const struct param_info_s __param__L1P_BW_X;
	const struct param_info_s __param__L1P_BW_Y;
	const struct param_info_s __param__L1P_BW_Z;
	const struct param_info_s __param__L1P_OBS_GAIN_X;
	const struct param_info_s __param__L1P_OBS_GAIN_Y;
	const struct param_info_s __param__L1P_OBS_GAIN_Z;
	const struct param_info_s __param__L1P_ADAPT_GAIN_X;
	const struct param_info_s __param__L1P_ADAPT_GAIN_Y;
	const struct param_info_s __param__L1P_ADAPT_GAIN_Z;
	const struct param_info_s __param__L1P_INIT_DIST_X;
	const struct param_info_s __param__L1P_INIT_DIST_Y;
	const struct param_info_s __param__L1P_INIT_DIST_Z;
	const struct param_info_s __param__L1P_ENGAGE_LEVEL;
	const struct param_info_s __param__L1P_ENABLE_DEBUG;
	const struct param_info_s __param__CAL_GYRO0_BWX0;
	const struct param_info_s __param__CAL_GYRO0_BWX1;
	const struct param_info_s __param__CAL_GYRO0_BWX2;
	const struct param_info_s __param__CAL_GYRO0_BWY0;
	const struct param_info_s __param__CAL_GYRO0_BWY1;
	const struct param_info_s __param__CAL_GYRO0_BWY2;
	const struct param_info_s __param__CAL_GYRO0_BWZ0;
	const struct param_info_s __param__CAL_GYRO0_BWZ1;
	const struct param_info_s __param__CAL_GYRO0_BWZ2;
	const struct param_info_s __param__CAL_MAG0_MXX;
	const struct param_info_s __param__CAL_MAG0_MXY;
	const struct param_info_s __param__CAL_MAG0_MXZ;
	const struct param_info_s __param__CAL_MAG0_MYX;
	const struct param_info_s __param__CAL_MAG0_MYY;
	const struct param_info_s __param__CAL_MAG0_MYZ;
	const struct param_info_s __param__CAL_MAG0_MZX;
	const struct param_info_s __param__CAL_MAG0_MZY;
	const struct param_info_s __param__CAL_MAG0_MZZ;
	const struct param_info_s __param__CAL_ACC0_BAX0;
	const struct param_info_s __param__CAL_ACC0_BAX1;
	const struct param_info_s __param__CAL_ACC0_BAX2;
	const struct param_info_s __param__CAL_ACC0_BAY0;
	const struct param_info_s __param__CAL_ACC0_BAY1;
	const struct param_info_s __param__CAL_ACC0_BAY2;
	const struct param_info_s __param__CAL_ACC0_BAZ0;
	const struct param_info_s __param__CAL_ACC0_BAZ1;
	const struct param_info_s __param__CAL_ACC0_BAZ2;
	const struct param_info_s __param__RC_MAP_FAILSAFE;
	const struct param_info_s __param__FW_FLARE_PMIN;
	const struct param_info_s __param__FW_FLARE_PMAX;
	const struct param_info_s __param__RV_YAW_P;
	const struct param_info_s __param__EXFW_HDNG_P;
	const struct param_info_s __param__EXFW_ROLL_P;
	const struct param_info_s __param__EXFW_PITCH_P;
	const unsigned int param_count;
};

extern const struct px4_parameters_t px4_parameters;
